# Generated by Django 5.2.15 on 2026-06-28 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(help_text='Short one-liner shown under the title', max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('live', 'Live'), ('wip', 'In Progress'), ('archived', 'Archived')], default='live', max_length=20)),
                ('color', models.CharField(default='#6FE3D2', help_text='Hex accent colour, e.g. #6FE3D2', max_length=7)),
                ('year', models.PositiveSmallIntegerField(default=2025)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('media_type', models.CharField(choices=[('none', 'No media'), ('image', 'Image upload'), ('video', 'Video URL')], default='none', max_length=10)),
                ('media_image', models.ImageField(blank=True, help_text='Upload a screenshot or banner (media_type must be "image")', null=True, upload_to='personal_projects/')),
                ('media_video_url', models.URLField(blank=True, help_text='Direct .mp4 URL (media_type must be "video")')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personal Project',
                'verbose_name_plural': 'Personal Projects',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='PersonalProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='personal_projects.personalproject')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['order'],
            },
        ),
    ]
