# Generated by Django 4.2.16 on 2026-06-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ghanshyam Desale', max_length=100)),
                ('tagline', models.TextField(default='Engineering high-performance digital products.')),
                ('email', models.EmailField(default='ghanshyamdesale1421@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91 7498770064', max_length=20)),
                ('location', models.CharField(default='Mumbai, India', max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('years_experience', models.PositiveSmallIntegerField(default=3)),
                ('available_for_work', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
