# Generated by Django 5.2.15 on 2026-06-28 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaultSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Auto-filled from label. Used as the tab id.', unique=True)),
                ('label', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='📁', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vault Section',
                'verbose_name_plural': 'Vault Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VaultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, help_text='Short copyable value — shortcut key, cert ID, port, etc.', max_length=500)),
                ('url', models.URLField(blank=True, help_text='Opens in new tab when clicked')),
                ('notes', models.TextField(blank=True, help_text='Extra hint shown below the title')),
                ('tags', models.JSONField(default=list, help_text='List of short label strings, e.g. ["Chrome", "Debug"]')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vault.vaultsection')),
            ],
            options={
                'verbose_name': 'Vault Item',
                'verbose_name_plural': 'Vault Items',
                'ordering': ['order'],
            },
        ),
    ]
