# Generated by Django 4.2.16 on 2026-06-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('entry_type', models.CharField(choices=[('education', 'Education'), ('work', 'Work'), ('achievement', 'Achievement'), ('future', 'Roadmap')], default='work', max_length=20)),
                ('tags', models.JSONField(default=list, help_text='List of tag strings')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Experience Entries',
                'ordering': ['order'],
            },
        ),
    ]
